tasks:
  - init: odoo-bin -r gitpod --addons-path=/workspace -d template1 -i base,odoo_skeleton_module -D /workspace/.odoo --stop-after-init
    command: odoo-bin -r gitpod --addons-path=/workspace -d template1 --dev all -D /workspace/.odoo
image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - littlefoxteam.vscode-python-test-adapter@0.3.16:tZ/6xOSSdKUaq6JCUVkD+A==`
    - mrorz.language-gettext@0.1.1:74p3WtjygwX9/E3GVChuUg==
    - Gruntfuggly.todo-tree@0.0.176:cbaxSjN5CtxoSnZ5Xvqh3g==